function setDefault()
  gpio.mode(5, gpio.OUTPUT)
  gpio.mode(6, gpio.OUTPUT)
  gpio.mode(7, gpio.OUTPUT)
  gpio.mode(8, gpio.OUTPUT)
  gpio.write(5, gpio.LOW)
  gpio.write(6, gpio.LOW)
  gpio.write(7, gpio.LOW)
  gpio.write(8, gpio.LOW)
end
